# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install --save-dev jest supertest

# Copy the rest of the application code
COPY . .

# Run the tests
CMD ["npm", "test"]
